engines:
    phpmd:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - "php"

ratings:
    paths:
        - "**.php"

exclude_paths:
    - "*app/DoctrineMigrations/*"
    - "*public/vendor/*"
    - "*vendor/*"
    - "*web/*"
