checks:
    php: true

coding_style:
    php: {  }

filter:
    excluded_paths:
        - app/*
        - bin/*
        - tests/*
        - vendor/*
        - web/*
        - kahlan-config.php

build:
    dependencies:
        before:
            -
                command: cp app/config/parameters.yml.dist app/config/parameters.yml
    environment:
        php:
            version: 7.1.0
    tests:
        override:
            -
                command: ant
                coverage:
                    file: "coverage.xml"
                    format: "php-clover"
