language: php
php:
  - '7.0.1'

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

env:
  global:
    - MIN_PHP=7.0.1

script:
  - php bin/phpunit -c tests/phpunit.xml --colors=always --verbose --coverage-clover=coverage.xml

services:
  - mysql

after_success:
  - bash <(curl -s https://codecov.io/bash)
