language: php
php:
  - '7.0'
#  - hhvm

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

env:
  global:
    - MIN_PHP=7.0.1

script:
  - php bin/phpunit -c tests/phpunit.xml --colors=always --verbose || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));

services:
  - mongodb
  - mysql
