services:
    # Models
    battleship.game.services.cell.model:
        class: EM\GameBundle\Model\CellModel
        arguments:
            - "@battleship.game.services.cell.state.repository"
    battleship.game.services.player.model:
        class: EM\GameBundle\Model\PlayerModel
        arguments:
            - "@battleship.game.services.player.repository"
            - "@battleship.game.services.player.type.repository"
    battleship.game.services.game.result.model:
        class: EM\GameBundle\Model\GameResultModel
        arguments:
            - "%battleship_game.game_results_per_page%"
            - "@battleship.game.services.game.result.repository"
    # AI
    battleship.game.services.ai.core.service:
        class: EM\GameBundle\Service\AI\AIService
        arguments:
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.ai.strategy.service"
    battleship.game.services.ai.strategy.service:
        class: EM\GameBundle\Service\AI\AIStrategyService
        arguments:
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.ai.strategy.processor"
    # Processors
    battleship.game.services.ai.strategy.processor:
        class: EM\GameBundle\Service\AI\AIStrategyProcessor
    battleship.game.services.game.processor:
        class: EM\GameBundle\Service\GameSystem\GameProcessor
        arguments:
            - "@battleship.game.services.ai.core.service"
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.player.model"
    # Repositories
    battleship.game.services.cell.state.repository:
        class: EM\GameBundle\Repository\CellStateRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\CellState
    battleship.game.services.player.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\Player
    battleship.game.services.player.type.repository:
        class: EM\GameBundle\Repository\PlayerTypeRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\PlayerType
    battleship.game.services.game.result.repository:
        class: EM\GameBundle\Repository\GameResultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\GameResult
