services:
    # Models
    battleship.game.services.cell.model:
        class: EM\GameBundle\Model\CellModel
        arguments:
            - "@battleship.game.services.cell.state.repository"
    battleship.game.services.player.model:
        class: EM\GameBundle\Model\PlayerModel
        arguments:
            - "@battleship.game.services.player.type.repository"
    battleship.game.services.game.model:
        class: EM\GameBundle\Model\GameModel
        arguments:
            - "@battleship.game.services.ai.core.service"
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.player.model"
            - "@doctrine.orm.entity_manager"
    battleship.game.services.game.result.model:
        class: EM\GameBundle\Model\GameResultModel
        arguments:
            - %battleship.game.config.game.results.per.page%
            - "@battleship.game.services.game.result.repository"
    # AI
    battleship.game.services.ai.core.service:
        class: EM\GameBundle\Service\AI\AIService
        arguments:
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.ai.strategy.service"
    battleship.game.services.ai.strategy.service:
        class: EM\GameBundle\Service\AI\AIStrategyService
        arguments:
            - "@battleship.game.services.cell.model"
            - "@battleship.game.services.ai.strategy.processor"
    # Processors
    battleship.game.services.ai.strategy.processor:
        class: EM\GameBundle\Service\AI\AIStrategyProcessor
    # Repositories
    battleship.game.services.cell.state.repository:
        class: EM\GameBundle\Repository\CellStateRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\CellState
    battleship.game.services.player.type.repository:
        class: EM\GameBundle\Repository\PlayerTypeRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\PlayerType
    battleship.game.services.game.result.repository:
        class: EM\GameBundle\Repository\GameResultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\GameResult
