services:
    # Event Listeners
#    battleship.game.response.listener:
#        class: EM\GameBundle\EventListener\GameResponseListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    battleship_game.listener.on_kernel_request:
        class: EM\GameBundle\EventListener\PlayerAuthorizationListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    # Models
    battleship_game.service.player_model:
        class: EM\GameBundle\Model\PlayerModel
        arguments:
            - "@battleship_game.repository.player"
    battleship_game.service.game_result_model:
        class: EM\GameBundle\Model\GameResultModel
        arguments:
            - "@battleship_game.repository.game_result"
            - "%battleship_game.setting.game_results_per_page%"
    # Game Processors
    battleship_game.service.game_processor:
        class: EM\GameBundle\Service\GameSystem\GameProcessor
        arguments:
            - "@battleship_game.service.ai_core"
            - "@battleship_game.service.player_model"
    # AI
    battleship_game.service.ai_core:
        class: EM\GameBundle\Service\AI\AIService
        arguments:
            - "@battleship_game.service.ai_strategy"
    battleship_game.service.ai_strategy:
        class: EM\GameBundle\Service\AI\AIStrategyService
        arguments:
            - "@battleship_game.service.ai_strategy_processor"
    battleship_game.service.ai_strategy_processor:
        class: EM\GameBundle\Service\AI\AIStrategyProcessor
    # Repositories
    battleship_game.repository.player:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\Player
    battleship_game.repository.game_result:
        class: EM\GameBundle\Repository\GameResultRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - EM\GameBundle\Entity\GameResult
    # Validators
    battleship_game.validator.game_initiation_request:
        class: EM\GameBundle\Validator\GameInitiationRequestValidator
        arguments:
            - "%battleship_game.setting.min_game_size%"
            - "%battleship_game.setting.max_game_size%"
            - "%battleship_game.setting.min_opponents_count%"
            - "%battleship_game.setting.max_opponents_count%"
