imports:
    - { resource: config_dev_common.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true
    intercept_redirects: false

nelmio_api_doc: ~
