project.foundation-bundle:
    resource: "@FoundationBundle/Resources/config/routing.yml"
    prefix:   /

project.game-bundle:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /
