NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/documentation

battleship-game:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /
