NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/documentation

foundation:
    resource: "@FoundationBundle/Resources/config/routing.yml"
    prefix:   /
battleship-game:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /
