EM\GameBundle\Response\StatisticsResponse:
    accessor_order: custom
    custom_accessor_order: [meta, results]

    xml_root_name: statistics

    properties:
        meta:
            type: array<string, integer>
            inline: false
            xml_key_value_pairs: true
        results:
            type: array<EM\GameBundle\Entity\GameResult>
            xml_list:
                inline: false
                entry_name: result
