EM\GameBundle\Entity\Cell:
    accessor_order: custom
    custom_accessor_order: [id, coordinate, flags]

    exclusion_policy: ALL

    xml_root_name: cell

    properties:
        id:
            type: integer
            expose: true
        coordinate:
            type: string
        flags:
            type: integer
            expose: true
