EM\GameBundle\Entity\Cell:
    accessor_order: custom
    custom_accessor_order: [id, coordinate, state]

    exclusion_policy: ALL

    xml_root_name: cell

    properties:
        id:
            type: integer
            expose: true
        coordinate:
            type: string
            xml_element:
                cdata: false
        mask:
            type: integer
            expose: true
