EM\GameBundle\Entity\GameResult:
    accessor_order: custom
    custom_accessor_order: [id, timestamp, player]

    exclusion_policy: ALL

    xml_root_name: gameResult

    properties:
        id:
            type: integer
            expose: true
        timestamp:
            type: DateTime
            expose: true
        player:
            type: EM\GameBundle\Entity\Player
            expose: true
