EM\GameBundle\Entity\Player:
    accessor_order: custom
    custom_accessor_order: [id, type, name]

    xml_root_name: player

    properties:
        id:
            type: integer
        type:
            type: integer
        name:
            type: string
            xml_element:
                cdata: false
