EM\GameBundle\Entity\Player:
    accessor_order: custom
    custom_accessor_order: [id, mask, name]

    xml_root_name: player

    properties:
        id:
            type: integer
        mask:
            type: integer
        name:
            type: string
            xml_element:
                cdata: false
