EM\GameBundle\Entity\Player:
    accessor_order: custom
    custom_accessor_order: [id, flag, name]

    xml_root_name: player

    properties:
        id:
            type: integer
        flag:
            type: integer
        name:
            type: string
